@startuml

object Bruger{
brugernavn
adgangskode
favoritter : liste
reviews : liste
}

object Spil{
spillerKapacitet : int liste
materialer : liste
kategorier : liste
}

object Review{
forfatter
rating : int
tekst
}

object Forum

object Ruleset

object Gameplay

object Statestik{
gennemsnitRating : decimal
antalKlik
varighed : tid
}

Bruger "0..*" --- "0..*" Spil : Gør til favorit
Review "0..*" --- "1" Spil : Tilhører
Bruger "1" --- "0..*" Review : Opretter
Forum "0..*" --- "0..*" Bruger
Spil "1" --- "1..*" Ruleset
Spil "1" --- "0..1" Gameplay
Spil "1" --- "1" Statestik

@enduml